-- MySQL Script generated by MySQL Workbench
-- Sun Jan  4 10:08:36 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema teemo_store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teemo` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE teemo;

-- -----------------------------------------------------
-- Table `t_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `t_role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL COMMENT '角色名称',
  `description` VARCHAR(256) NULL COMMENT '角色描述',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
COMMENT = '角色表';


-- -----------------------------------------------------
-- Table `t_role_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `t_role_permission` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `role_id` BIGINT NOT NULL COMMENT '角色ID',
  `perm_res_type` INT NOT NULL COMMENT '权限资源类型',
  `perm_res_id` VARCHAR(128) NOT NULL COMMENT '权限资源id',
  `perm_res_op_mask` INT NOT NULL COMMENT '权限资源的操作掩码',
  `perm_res_prop` TEXT NULL COMMENT '权限资源的属性',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `role_permission` (`role_id` ASC, `perm_res_type` ASC, `perm_res_id` ASC))
ENGINE = InnoDB
COMMENT = '角色权限表';


-- -----------------------------------------------------
-- Table `t_backend_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `t_backend_user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL COMMENT '用户名',
  `password` VARCHAR(50) NULL COMMENT '密码',
  `salt` VARCHAR(50) NULL COMMENT '密码的盐值',
  `email` VARCHAR(128) NULL COMMENT '邮件',
  `phone` VARCHAR(59) NULL COMMENT '电话',
  `display_name` VARCHAR(50) NOT NULL COMMENT '显示的名称',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `last_login_time` TIMESTAMP NULL COMMENT '最后一次登录时间',
  `status` INT NOT NULL DEFAULT 0,
  `type` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
COMMENT = '后台管理用户表';


-- -----------------------------------------------------
-- Table `t_backend_user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `t_backend_user_role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `role_id` BIGINT NOT NULL COMMENT '角色ID',
  `backend_user_id` BIGINT NOT NULL COMMENT '所属后台用户ID',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  INDEX `backend_user_id` (`backend_user_id` ASC),
  INDEX `role_id` (`role_id` ASC),
  UNIQUE INDEX `role_id_backend_user_id_UNIQUE` (`role_id` ASC, `backend_user_id` ASC))
ENGINE = InnoDB
COMMENT = '后台用户角色表';

-- -----------------------------------------------------
-- Table `t_edu_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `t_edu_category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `parent_id` BIGINT NULL COMMENT '父类ID',
  `name` VARCHAR(45) NOT NULL COMMENT '类别名称',
  `displayName` varchar(45) DEFAULT NULL COMMENT '列别显示名称',
  `status` INT NOT NULL COMMENT '状态(启用，停用)',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
COMMENT = '教育内容类别表';

-- -----------------------------------------------------
-- Table `t_edu_article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `t_edu_article` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cat_id` BIGINT NOT NULL COMMENT '类别ID',
  `type` INT NOT NULL COMMENT '文章的类型',
  `sub_type` INT NOT NULL COMMENT '文章的子类型',
  `status` INT NOT NULL COMMENT '状态',
  `e_status` INT NOT NULL COMMENT '编辑状态',
  `mid`  BIGINT DEFAULT NULL COMMENT '媒体id',
  `eid`  BIGINT DEFAULT NULL COMMENT '编辑id',
  `aid`  BIGINT DEFAULT NULL COMMENT '审核人id',
  `code` varchar(24) NOT NULL COMMENT '唯一编码',
  `title` varchar(128) DEFAULT NULL COMMENT '标题',
  `keyword` varchar(128) DEFAULT NULL COMMENT '关键词',
  `content` LONGTEXT DEFAULT NULL COMMENT '内容',
  `des` TEXT DEFAULT NULL COMMENT '简介',
  `resource` TEXT DEFAULT NULL COMMENT '资源',
  `conf` TEXT DEFAULT NULL COMMENT '配置',
  `ref` SMALLINT DEFAULT NULL COMMENT '是否引用',
  `ref_id` BIGINT DEFAULT NULL COMMENT '引用的id',
  `ct` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `ut` TIMESTAMP NULL COMMENT '更新时间',
  `at` TIMESTAMP NULL COMMENT '审核时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code` (`code` ASC),
  INDEX `type_sub_type` (`type`,`sub_type` ASC),
  INDEX `title` (`title` ASC),
  INDEX `mid` (`mid` ASC),
  INDEX `eid` (`eid` ASC),
  INDEX `cat_id` (`cat_id` ASC),
  INDEX `status` (`status` ASC),
  INDEX `ct` (`ct` ASC))
ENGINE = InnoDB
COMMENT = '教育文章';

-- -----------------------------------------------------
-- Table `t_edu_push`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `t_edu_push` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `article_id` BIGINT NOT NULL COMMENT '文章ID',
  `cat_id` BIGINT NOT NULL COMMENT '类别ID',
  `type` INT NOT NULL COMMENT '文章的类型',
  `status` INT NOT NULL COMMENT '状态',
  `e_status` INT NOT NULL COMMENT '编辑状态',
  `eid`  BIGINT DEFAULT NULL COMMENT '编辑id',
  `aid`  BIGINT DEFAULT NULL COMMENT '审核人id',
  `min_age` INT DEFAULT NULL COMMENT '最小年龄',
  `max_age` INT DEFAULT NULL COMMENT '最大年龄',
  `sex` SMALLINT DEFAULT NULL COMMENT '性别',
  `targets` VARCHAR(512) DEFAULT NULL COMMENT '推送目标',
  `pat` TIMESTAMP NULL COMMENT '推送的时间',
  `ct` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `ut` TIMESTAMP NULL COMMENT '更新时间',
  `at` TIMESTAMP NULL COMMENT '审核时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `article_id` (`article_id` ASC),
  INDEX `cat_id` (`cat_id` ASC),
  INDEX `type` (`cat_id` ASC),
  INDEX `e_status` (`e_status` ASC),
  INDEX `status` (`status` ASC),
  INDEX `min_age` (`min_age` ASC),
  INDEX `max_age` (`max_age` ASC),
  INDEX `pat` (`pat` ASC))
ENGINE = InnoDB
COMMENT = '教育推送';

-- -----------------------------------------------------
-- Table `t_edu_push_target`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `t_edu_push_target` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `pid` BIGINT NOT NULL COMMENT '推送id',
  `target` VARCHAR(20) NOT NULL COMMENT '推送的产品',
  `ct` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `ut` TIMESTAMP NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pid_target_UNIQUE` (`pid`,`target` ASC),
  INDEX `pid` (`pid` ASC))
ENGINE = InnoDB
COMMENT = '教育推送目标';

-- -----------------------------------------------------
-- Table `t_edu_media_channel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `t_edu_media_channel` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` varchar(24) NOT NULL COMMENT '唯一编码',
  `name` varchar(128) NOT NULL COMMENT '名称',
  `url` varchar(256) NULL DEFAULT NULL COMMENT '官网',
  `resource` TEXT DEFAULT NULL COMMENT '资源',
  `status` INT NOT NULL COMMENT '状态',
  `ct` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `ut` TIMESTAMP NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  INDEX `name` (`name` ASC),
  UNIQUE INDEX `code` (`code` ASC))
ENGINE = InnoDB
COMMENT = '教育媒体渠道';

-- -----------------------------------------------------
-- Table `t_edu_media_res`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `t_edu_media_res` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `eid`  BIGINT DEFAULT NULL COMMENT '编辑id',
  `type` INT NOT NULL COMMENT '类型',
  `status` INT NOT NULL COMMENT '状态',
  `des` TEXT NULL COMMENT '简介',
  `lp` VARCHAR(512) NULL COMMENT '本地路径',
  `rp` VARCHAR(512) NULL COMMENT '远程路径',
  `conf` TEXT NULL COMMENT '配置',
  `ct` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `ut` TIMESTAMP NULL COMMENT '更新时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '教育媒体资源';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
